import { defineSchema } from "convex/server";
import {
  profiles,
  games,
  gamePlayers,
  gameSpectators,
  joinRequests,
  gamePinAttempts,
  gameSessions,
  gamePlayerRoles,
  nightPhaseSessions,
  votingSessions,
  votes,
  cardPickingSessions,
  gameLogs,
  gameLogPlayers,
  playerStats,
  playerRatings,
  adminAuditLog,
  communityMessages,
  communityReadState,
  gameBroadcasts,
} from "./tables";

const schema = defineSchema({
  profiles,
  games,
  gamePlayers,
  gameSpectators,
  joinRequests,
  gamePinAttempts,
  gameSessions,
  gamePlayerRoles,
  nightPhaseSessions,
  votingSessions,
  votes,
  cardPickingSessions,
  gameLogs,
  gameLogPlayers,
  playerStats,
  playerRatings,
  adminAuditLog,
  communityMessages,
  communityReadState,
  gameBroadcasts,
});

export default schema;
